name: linux-desktop-manager
version: '0.2'
summary: Remote manager for Linux desktops
description: |
  Linux Desktop Manager allows you to remotely manage your desktop.

  Note: This is not a RDP client.

grade: stable
confinement: devmode

apps:
  linux-desktop-manager:
    command: linux-desktop-manager
    plugs:
      - network

parts:
  linux-desktop-manager:
    plugin: python
    source: .
    requirements: requirements.txt
    build-packages:
      - pkg-config
      - libdbus-1-dev
      - libdbus-glib-1-dev

#slots:
#  kde-screensaver-dbus:
#    interface: dbus
#    name: org.kde.screensaver
#    bus: session
